name: Bug反馈
description: 报告在浏览网站中发现的问题。
title: "[Bug]: "
labels: ["类型:bug"]
assignees:
  - QingFeng-awa
body:
  - type: checkboxes
    attributes:
      label: 我确认没有相同的issue已打开。
      description: 您必须确认此选项,否则您的issue可能会无条件锁定&关闭。
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 我已明白并知晓,如果我不按照模板指示填写issue,则我的issue可能会无条件锁定&关闭。
      description: 您必须确认此选项,否则您的issue可能会无条件锁定&关闭。
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 遇到了什么问题/发现了什么问题?
    validations:
      required: true
  - type: textarea
    id: right
    attributes:
      label: 期望的正确结果是?
      description: 您认为该正常出现什么?
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其它信息
      description: 非必填选项。
    validations:
      required: false