name: Add Dev Label on Comment

on:
  issue_comment:
    types: [created]

jobs:
  add_dev_label:
    runs-on: ubuntu-latest

    steps:
    - name: Check for /dev Command and Add Label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: |
        echo "Comment Body: $COMMENT_BODY"  # 输出评论内容以供调试
        
        if [[ "$COMMENT_BODY" == "/dev" ]]; then
          LABEL_TO_ADD="dev"
        else
          echo "No relevant command found, skipping action."
          exit 0
        fi

        LABEL_TO_ADD_ENCODED=$(echo -n "$LABEL_TO_ADD" | jq -sRr @uri)

        # 添加标签 "dev"
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" \
          -d "{\"labels\": [\"$LABEL_TO_ADD\"]}" \
          "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels"
